path: /home/mpavlov/YOLO/images/
train: train
val: valid
test: test
names:
  0: Acroptilon repens
  1: Ambrosia_artemisiifolia
  2: Ambrosia_tridia
  3: color_checker
  4: Convolvulus_arvenis
  5: Delphinium consolida
  6: Galium_aparine
  7: Onopordum_acanthium
  8: Polygonum_convolvulus
  9: Silene_latifolia
  10: Sinapsis_arvenis
  11: Turgenia_latifolia
